// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNsoVftBxPI2eIBC2zKTr64gBGV-TyFp4',
    appId: '1:583577603441:web:b914c17a955367f947fad0',
    messagingSenderId: '583577603441',
    projectId: 'crud-operation-22557',
    authDomain: 'crud-operation-22557.firebaseapp.com',
    storageBucket: 'crud-operation-22557.firebasestorage.app',
    measurementId: 'G-CJ4JJ54T61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk9QgO53PLHs17XbLrnHR2EmiW0Lyz6H8',
    appId: '1:583577603441:android:05a04d142831985b47fad0',
    messagingSenderId: '583577603441',
    projectId: 'crud-operation-22557',
    storageBucket: 'crud-operation-22557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKigyPcsnDEbIc_bknjVTo4FyzMA70WfA',
    appId: '1:583577603441:ios:6023dd732bbe212e47fad0',
    messagingSenderId: '583577603441',
    projectId: 'crud-operation-22557',
    storageBucket: 'crud-operation-22557.firebasestorage.app',
    iosBundleId: 'com.example.crudOperation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKigyPcsnDEbIc_bknjVTo4FyzMA70WfA',
    appId: '1:583577603441:ios:6023dd732bbe212e47fad0',
    messagingSenderId: '583577603441',
    projectId: 'crud-operation-22557',
    storageBucket: 'crud-operation-22557.firebasestorage.app',
    iosBundleId: 'com.example.crudOperation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNsoVftBxPI2eIBC2zKTr64gBGV-TyFp4',
    appId: '1:583577603441:web:0bd57fdae36a879247fad0',
    messagingSenderId: '583577603441',
    projectId: 'crud-operation-22557',
    authDomain: 'crud-operation-22557.firebaseapp.com',
    storageBucket: 'crud-operation-22557.firebasestorage.app',
    measurementId: 'G-ZGCR0W3YDC',
  );
}
