// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZT5dCoAcj1tJhe3QaY8QaEm3-9vnqhac',
    appId: '1:430072484098:web:c68d065a07325544c7321b',
    messagingSenderId: '430072484098',
    projectId: 'fir-test-baadd',
    authDomain: 'fir-test-baadd.firebaseapp.com',
    storageBucket: 'fir-test-baadd.firebasestorage.app',
    measurementId: 'G-QXJTX1SYNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARQSnJwUctZN0VQVUCnHfG3CD1Gma2uc4',
    appId: '1:430072484098:android:5f9f19a3fea88a94c7321b',
    messagingSenderId: '430072484098',
    projectId: 'fir-test-baadd',
    storageBucket: 'fir-test-baadd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSuCgepA2tUR4Y0Wbi2gsJVLwS2MDiGZo',
    appId: '1:430072484098:ios:ff02f86443301f4fc7321b',
    messagingSenderId: '430072484098',
    projectId: 'fir-test-baadd',
    storageBucket: 'fir-test-baadd.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSuCgepA2tUR4Y0Wbi2gsJVLwS2MDiGZo',
    appId: '1:430072484098:ios:ff02f86443301f4fc7321b',
    messagingSenderId: '430072484098',
    projectId: 'fir-test-baadd',
    storageBucket: 'fir-test-baadd.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZT5dCoAcj1tJhe3QaY8QaEm3-9vnqhac',
    appId: '1:430072484098:web:899c4ced36903c66c7321b',
    messagingSenderId: '430072484098',
    projectId: 'fir-test-baadd',
    authDomain: 'fir-test-baadd.firebaseapp.com',
    storageBucket: 'fir-test-baadd.firebasestorage.app',
    measurementId: 'G-MJ8R9P1CQX',
  );
}
